import type { Professional, SkillCategory } from '@/types';

export const SKILL_CATEGORIES: SkillCategory[] = [
    { id: 'all', label: 'Todos' },
    { id: 'development', label: 'Desenvolvimento' },
    { id: 'design', label: 'Design' },
    { id: 'management', label: 'Gerenciamento' },
    { id: 'marketing', label: 'Marketing' },
];

export const SKILL_TO_CATEGORY: { [key: string]: SkillCategory['id'] } = {
    'React': 'development',
    'Node.js': 'development',
    'TypeScript': 'development',
    'Next.js': 'development',
    'Vue.js': 'development',
    'Angular': 'development',
    'Python': 'development',
    'Django': 'development',
    'Ruby on Rails': 'development',
    'DevOps': 'development',
    'AWS': 'development',
    'Docker': 'development',
    'UI/UX Design': 'design',
    'Figma': 'design',
    'Adobe XD': 'design',
    'Sketch': 'design',
    'Brand Identity': 'design',
    'Illustration': 'design',
    'Project Management': 'management',
    'Agile': 'management',
    'Scrum': 'management',
    'Product Management': 'management',
    'SEO': 'marketing',
    'Content Marketing': 'marketing',
    'Social Media': 'marketing',
};

export const MOCK_PROS: Professional[] = [
    {
        id: '1',
        name: 'Lucas Almeida',
        role: 'Desenvolvedor Front-end Sênior',
        avatar: 'https://picsum.photos/seed/1/100/100',
        skills: ['React', 'TypeScript', 'Next.js', 'GraphQL'],
        rating: 4.9,
        experience: '8 anos de experiência em desenvolvimento de aplicações web modernas e escaláveis. Especialista em ecossistema React.',
        contact: 'lucas.almeida@email.com',
        averageResponseTime: '25m',
        averageDeliveryTime: '2d',
        hourlyRate: 250,
        portfolio: [
            { title: 'E-commerce de Moda', description: 'Plataforma completa com Next.js e Shopify.', image: 'https://picsum.photos/seed/101/600/400', link: '#' },
            { title: 'Dashboard Analítico', description: 'Dashboard interativo com D3.js e React.', image: 'https://picsum.photos/seed/102/600/400', link: '#' },
        ],
    },
    {
        id: '2',
        name: 'Juliana Costa',
        role: 'UI/UX Designer Pleno',
        avatar: 'https://picsum.photos/seed/2/100/100',
        skills: ['UI/UX Design', 'Figma', 'Adobe XD', 'User Research'],
        rating: 5.0,
        satisfaction: 100,
        experience: '5 anos criando interfaces intuitivas e experiências de usuário memoráveis para startups e grandes empresas.',
        contact: 'juliana.costa@email.com',
        averageResponseTime: '15m',
        averageDeliveryTime: '3d',
        hourlyRate: 180,
        portfolio: [
            { title: 'Aplicativo de Meditação', description: 'Design de interface e experiência para app iOS e Android.', image: 'https://picsum.photos/seed/103/600/400', link: '#' },
            { title: 'Sistema de Design System', description: 'Criação de um Design System completo em Figma.', image: 'https://picsum.photos/seed/104/600/400', link: '#' },
        ],
    },
    {
        id: '3',
        name: 'Rafael Oliveira',
        role: 'Desenvolvedor Back-end Especialista',
        avatar: 'https://picsum.photos/seed/3/100/100',
        skills: ['Node.js', 'Python', 'Django', 'AWS', 'DevOps'],
        rating: 4.8,
        experience: '10 anos de experiência em arquitetura de microsserviços, APIs REST/GraphQL e infraestrutura em nuvem.',
        contact: 'rafael.oliveira@email.com',
        averageResponseTime: '45m',
        averageDeliveryTime: '4d',
        hourlyRate: 300,
        portfolio: [
            { title: 'API para Fintech', description: 'Desenvolvimento de API segura e de alta performance para uma fintech.', image: 'https://picsum.photos/seed/105/600/400', link: '#' },
        ],
    },
    {
        id: '4',
        name: 'Carla Martins',
        role: 'Gerente de Projetos Agile',
        avatar: 'https://picsum.photos/seed/4/100/100',
        skills: ['Project Management', 'Agile', 'Scrum', 'Jira'],
        rating: 4.9,
        experience: 'Gerente de projetos certificada (PMP, CSM) com foco em otimizar fluxos de trabalho e garantir entregas de valor.',
        contact: 'carla.martins@email.com',
        averageResponseTime: '10m',
        averageDeliveryTime: 'N/A',
        hourlyRate: 220,
        portfolio: [],
    },
    {
        id: '5',
        name: 'Bruno Gomes',
        role: 'Desenvolvedor Full-stack',
        avatar: 'https://picsum.photos/seed/5/100/100',
        skills: ['React', 'Node.js', 'Vue.js', 'Docker'],
        rating: 4.7,
        experience: 'Desenvolvedor versátil com 6 anos de experiência, apaixonado por construir produtos de ponta a ponta.',
        contact: 'bruno.gomes@email.com',
        averageResponseTime: '35m',
        averageDeliveryTime: '3d',
        hourlyRate: 230,
        portfolio: [
            { title: 'Plataforma SaaS', description: 'Construção de um SaaS de gestão de tarefas com Vue.js e Node.js.', image: 'https://picsum.photos/seed/106/600/400', link: '#' },
        ],
    },
    {
        id: '6',
        name: 'Fernanda Lima',
        role: 'Especialista em Marketing Digital',
        avatar: 'https://picsum.photos/seed/6/100/100',
        skills: ['SEO', 'Content Marketing', 'Social Media', 'Google Analytics'],
        rating: 4.9,
        experience: '7 anos ajudando marcas a crescerem online através de estratégias de conteúdo e performance.',
        contact: 'fernanda.lima@email.com',
        averageResponseTime: '20m',
        averageDeliveryTime: '5d',
        hourlyRate: 190,
        portfolio: [],
    },
    {
        id: '7',
        name: 'Gustavo Pereira',
        role: 'Brand Designer',
        avatar: 'https://picsum.photos/seed/7/100/100',
        skills: ['Brand Identity', 'Illustration', 'Figma', 'Adobe Illustrator'],
        rating: 5.0,
        satisfaction: 99,
        experience: 'Designer premiado, especializado em criar identidades visuais marcantes e sistemas de marca consistentes.',
        contact: 'gustavo.pereira@email.com',
        averageResponseTime: '50m',
        averageDeliveryTime: '7d',
        hourlyRate: 280,
        portfolio: [
            { title: 'Identidade Visual para Startup', description: 'Criação de logo, paleta de cores e guia de estilo.', image: 'https://picsum.photos/seed/107/600/400', link: '#' },
            { title: 'Ilustrações para App', description: 'Conjunto de ilustrações personalizadas para um aplicativo de viagens.', image: 'https://picsum.photos/seed/108/600/400', link: '#' },
        ],
    },
    {
        id: '8',
        name: 'Mariana Santos',
        role: 'Product Manager',
        avatar: 'https://picsum.photos/seed/8/100/100',
        skills: ['Product Management', 'Agile', 'User Research', 'Roadmap'],
        rating: 4.8,
        experience: 'Líder de produto com histórico de lançamento de produtos digitais de sucesso, do conceito à monetização.',
        contact: 'mariana.santos@email.com',
        averageResponseTime: '30m',
        averageDeliveryTime: 'N/A',
        hourlyRate: 260,
        portfolio: [],
    },
    {
        id: '9',
        name: 'Thiago Alves',
        role: 'Desenvolvedor Mobile (React Native)',
        avatar: 'https://picsum.photos/seed/9/100/100',
        skills: ['React Native', 'TypeScript', 'Firebase', 'GraphQL'],
        rating: 4.9,
        experience: 'Especialista em desenvolvimento de aplicativos móveis multiplataforma com React Native, focado em performance e UX.',
        contact: 'thiago.alves@email.com',
        averageResponseTime: '40m',
        averageDeliveryTime: '4d',
        hourlyRate: 240,
        portfolio: [
            { title: 'App de Social Commerce', description: 'Aplicativo de compras sociais com React Native e Firebase.', image: 'https://picsum.photos/seed/109/600/400', link: '#' },
        ],
    },
    {
        id: '10',
        name: 'Beatriz Rocha',
        role: 'Desenvolvedora Angular Sênior',
        avatar: 'https://picsum.photos/seed/10/100/100',
        skills: ['Angular', 'TypeScript', 'RxJS', 'NgRx'],
        rating: 4.7,
        experience: '7 anos construindo aplicações enterprise complexas e de alta performance com o framework Angular.',
        contact: 'beatriz.rocha@email.com',
        averageResponseTime: '1h',
        averageDeliveryTime: '3d',
        hourlyRate: 240,
        portfolio: [],
    },
];
